image: debian:latest

stages:
  - build
  - test

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

before_script:
  - chmod +x ./build.sh
  - ./build.sh prepare


build_service:
  stage: build
  script:
    - ./build.sh build
  artifacts:
    paths:
      - release
    expire_in: 1 week
  only:
    - main

test_service:
  stage: test
  script:
    - ./build.sh test
  only:
    - main
